# Generated by Django 6.1.1 on 2026-10-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_coupon_remove_order_product_remove_order_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("COD", "Cash on Delivery"),
                    ("bKash", "bKash Send Money"),
                    ("Nagad", "Nagad Send Money"),
                    ("Rocket", "Rocket Send Money"),
                ],
                default="COD",
                max_length=20,
            ),
        ),
    ]
